#!/bin/sh
# Thanks to https://github.com/overshard/docker-mumble/blob/master/scripts/start for this one
# -----------------------------------------------------------------------------
# docker-mumble /start script
#
# Authors: Isaac Bythewood
# -----------------------------------------------------------------------------

INI_PATH=/data/mumble-server.ini

# Set Mumble SuperUser password
if [ ! -f /data/superuser_password.txt ]
then
    SUPERUSER_PASSWORD=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;`
    echo $SUPERUSER_PASSWORD > /data/superuser_password.txt
    murmurd -ini $INI_PATH -supw $SUPERUSER_PASSWORD
    sleep 3
    echo
    echo "# ------------------------------------------------------------------------------"
    echo "# SuperUser Password"
    echo "#"
    echo "# Password: $SUPERUSER_PASSWORD"
    echo "#"
    echo "# Connect to the server as SuperUser and setup an admin user."
    echo "# ------------------------------------------------------------------------------"
    echo
fi
/usr/sbin/murmurd -ini $INI_PATH -fg -v
